In [3]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
%run Scraping_2024_PFR.ipynb
%run scraping_past_years.ipynb

In [14]:
the_df = pd.concat([ten_yr, df], ignore_index=True)

,Player,Pos,School,College,Ht,Wt,40yd,Vertical,Bench,Broad Jump,3Cone,Shuttle,Year
0,Israel Abanikanda,RB,Pittsburgh,College Stats,5-10,216,,,,,,,2023
1,Yasir Abdullah,LB,Louisville,College Stats,6-1,237,4.47,36.5,,129,,,2023
2,Devon Achane,RB,Texas A&M,College Stats,5-9,188,4.32,33.0,,,,,2023
3,Jordan Addison,WR,USC,College Stats,5-11,173,4.49,34.0,,122,,,2023
4,Adetomiwa Adebawore,DE,Northwestern,College Stats,6-2,282,4.49,37.5,27,125,,,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3827,Avery Williamson,ILB,Kentucky,College Stats,6-1,246,4.66,30.5,25,120,7.11,4.07,2014
3828,Albert Wilson,WR,Georgia State,College Stats,5-9,202,4.43,37.5,10,123,7.00,4.21,2014
3829,Kerry Wynn,DE,Richmond,,6-5,266,4.97,34.0,31,113,,,2014
3830,David Yankey,OG,Stanford,College Stats,6-6,315,5.48,28.5,22,103,7.81,4.86,2014
3831,Jordan Zumwalt,OLB,UCLA,College Stats,6-4,235,4.76,33.0,,116,6.99,4.25,2014

In [13]:
positions = ['QB', 'RB', 'WR', 'TE', 'OT', 'G', 'C', 'EDGE', 'DT', 'DE', 'LB', 'CB', 'DB', 'K', 'P']

#initialize dictionary
filtered_dfs = {}

# run over each position
for position in positions:
    if position == 'G':
        filtered_dfs[position] = the_df[the_df['Pos'].isin(['G', 'OG', 'OL'])].copy()
    elif position == 'DB':
        filtered_dfs[position] = the_df[the_df['Pos'].isin(['SAF', 'DB', 'S'])].copy()
    elif position == 'LB':
        filtered_dfs[position] = the_df[the_df['Pos'].isin(['LB', 'ILB', 'OLB'])].copy()
    elif position =='RB':
        filtered_dfs[position] = the_df[the_df['Pos'].isin(['RB', 'FB'])]
    elif position == 'C':
        filtered_dfs[position] = the_df[the_df['Pos'].isin(['C', 'LS'])]
    else:
        filtered_dfs[position] = the_df[the_df['Pos'] == position].copy()

# Access filtered DataFrames by position
the_qb_df = filtered_dfs['QB']
the_rb_df = filtered_dfs['RB']
the_wr_df = filtered_dfs['WR']
the_te_df = filtered_dfs['TE']
the_ot_df = filtered_dfs['OT']
the_g_df = filtered_dfs['G']
the_c_df = filtered_dfs['C']
the_edge_df = filtered_dfs['EDGE']
the_dt_df = filtered_dfs['DT']
the_de_df = filtered_dfs['DE']
the_lb_df = filtered_dfs['LB']
the_cb_df = filtered_dfs['CB']
the_db_df = filtered_dfs['DB']
the_k_df = filtered_dfs['K']
the_p_df = filtered_dfs['P']

display(the_qb_df)

,Player,Pos,School,College,Ht,Wt,40yd,Vertical,Bench,Broad Jump,3Cone,Shuttle,Year
13,Tyson Bagent,QB,Shepherd,,6-3,213,4.79,36.0,,120,6.95,4.36,2023
25,Stetson Bennett,QB,Georgia,College Stats,5-11,192,4.67,33.5,,118,,4.20,2023
58,Malik Cunningham,QB,Louisville,College Stats,6-0,192,4.53,,,,,,2023
70,Max Duggan,QB,TCU,College Stats,6-2,207,4.52,30.5,,116,7.26,4.45,2023
96,Jake Haener,QB,Fresno St.,College Stats,6-0,207,,35.0,,114,7.01,,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3763,Tom Savage,QB,Pittsburgh,College Stats,6-4,228,4.97,27.0,,105,7.33,4.36,2014
3767,Connor Shaw,QB,South Carolina,College Stats,6-0,206,4.66,34.0,,116,7.07,4.33,2014
3796,Logan Thomas,QB,Virginia Tech,College Stats,6-6,248,4.61,35.5,,118,7.05,4.18,2014
3809,Dustin Vaughan,QB,West Texas A&M,,6-5,235,4.95,29.0,,108,7.25,4.43,2014
3819,Keith Wenning,QB,Ball State,College Stats,6-3,218,5.00,28.0,,100,7.07,4.25,2014